services:
  prusa-camera:
    container_name: prusa-camera
    image: linuxserver/ffmpeg:arm32v7-5.1.2
    restart: always
    entrypoint: /bin/bash
    command: /upload.sh
    env_file:
      - .env
    devices:
      - /dev/video0:/dev/video0
    volumes:
      - ./upload.sh:/upload.sh